{
 "title": "Traces",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "services",
    "label": "services",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "All traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "limit": 20, "query": "{}", "tableType": "traces" }
   ]
  }
 ]
}
{
 "title": "Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "jobs", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 }, "options": { "content": "# GRPC Client" } },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 }, "options": { "content": "# GRPC Server" } },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Throughput (rpm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_duration_milliseconds_count[5m])*60)",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Throughput (rpm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_duration_milliseconds_count[5m])*60)",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Throughput per method (rpm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (rpc_method) (rate(rpc_client_duration_milliseconds_count{job=\"grpcclient\"}[5m])*60)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Throughput per method (rpm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (rpc_method) (rate(rpc_server_duration_milliseconds_count{job=\"grpcserver\"}[5m])*60)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rpc_client_duration_milliseconds_sum{job=\"grpcclient\"})\n/\nsum(rpc_client_duration_milliseconds_count{job=\"grpcclient\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Average latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(rpc_server_duration_milliseconds_sum{job=\"grpcserver\"})\n/\nsum(rpc_server_duration_milliseconds_count{job=\"grpcserver\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Average latency per method (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (rpc_method) (rpc_client_duration_milliseconds_sum{job=\"grpcclient\"})\n/\nsum by (rpc_method) (rpc_client_duration_milliseconds_count{job=\"grpcclient\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average latency per method (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by (rpc_method) (rpc_client_duration_milliseconds_sum{job=\"grpcclient\"})\n/\nsum by (rpc_method) (rpc_client_duration_milliseconds_count{job=\"grpcclient\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Error rate per method (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (service, span_name) (rate(traces_spanmetrics_latency_count{service=\"grpcclient\", status_code=\"STATUS_CODE_ERROR\"}[5m])*60)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error rate per method (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum by (service, span_name) (rate(traces_spanmetrics_latency_count{service=\"grpcserver\", status_code=\"STATUS_CODE_ERROR\"}[5m])*60)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}
{
 "title": "Logs",
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{k8s_namespace_name=\"default\",k8s_container_name=\"grpcclient\"} | logfmt | line_format `{{.log}}` | json | label_format service_name=service_name_extracted"
    }
   ]
  }
 ]
}