### Variables

# Datasources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      access: proxy
      orgId: 1
      url: http://tempo.default.svc.cluster.local:3100
      basicAuth: false
      isDefault: true
      version: 1
      editable: false
      apiVersion: 1
      uid: tempo
      jsonData:
        httpMethod: GET
        serviceMap:
          datasourceUid: prometheus

# Dashboard providers
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'traces'
      orgId: 1
      folder: ''
      type: file
      updateIntervalSeconds: 10
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/traces

# Dashboards
dashboards:
  traces:
    dashboard:
      datasource: Tempo
      json: |
        {
          "annotations": {
            "list": [
              {
                "builtIn": 1,
                "datasource": {
                  "type": "grafana",
                  "uid": "-- Grafana --"
                },
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "type": "dashboard"
              }
            ]
          },
          "editable": true,
          "fiscalYearStartMonth": 0,
          "graphTooltip": 0,
          "id": 1,
          "links": [],
          "panels": [
            {
              "datasource": {
                "type": "tempo",
                "uid": "tempo"
              },
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "thresholds"
                  },
                  "custom": {
                    "align": "auto",
                    "cellOptions": {
                      "type": "auto"
                    },
                    "inspect": false
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  }
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 24,
                "x": 0,
                "y": 0
              },
              "id": 1,
              "options": {
                "cellHeight": "sm",
                "footer": {
                  "countRows": false,
                  "fields": "",
                  "reducer": [
                    "sum"
                  ],
                  "show": false
                },
                "showHeader": true
              },
              "pluginVersion": "10.4.1",
              "targets": [
                {
                  "datasource": {
                    "type": "tempo",
                    "uid": "tempo"
                  },
                  "limit": 20,
                  "query": "{}",
                  "queryType": "traceql",
                  "refId": "A",
                  "tableType": "traces"
                }
              ],
              "title": "All traces",
              "type": "table"
            }
          ],
          "schemaVersion": 39,
          "tags": [],
          "templating": {
            "list": [
              {
                "current": {
                  "selected": true,
                  "text": [
                    "grpcserver"
                  ],
                  "value": [
                    "grpcserver"
                  ]
                },
                "datasource": {
                  "type": "tempo",
                  "uid": "tempo"
                },
                "definition": "",
                "description": "Name of the services.",
                "hide": 0,
                "includeAll": false,
                "label": "services",
                "multi": true,
                "name": "services",
                "options": [],
                "query": {
                  "label": "service.name",
                  "refId": "TempoDatasourceVariableQueryEditor-VariableQuery",
                  "type": 1
                },
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 0,
                "type": "query"
              }
            ]
          },
          "time": {
            "from": "now-15m",
            "to": "now"
          },
          "timepicker": {},
          "timezone": "browser",
          "title": "Traces",
          "uid": "adjthdkki4zr4c",
          "version": 3,
          "weekStart": ""
        }

